---
title: "Exploratory"
output: html_document
---

## Разведочный анализ данных и постановка задачи

Мы с вами поговорили про основы разведочного аналаза данных (lab_04) и про основные методы обработки и агрегации данных (lab_05). Кроме того, на лекции мы обсуждали тесты.

Сегодня вы попробуете применить ваши знания к реальным данным, про которые вы почти ничего не знаете. Это будет частью вашей домашней работы.

Загрузим необходимые данные с которыми вам предстоит работать:

```{r}
Customer_demographics <- read.csv("~/shared/minor2_2016/data/Customer_demographics.csv", sep = ";")
Product_sales <- read.csv("~/shared/minor2_2016/data/Product_sales.csv", sep = ";")
```

Данные связанны между собой, возможно, вам стоит объединить их в одну табличку с помощью *join*, по полю *Customer.ID*.

Ваша задача расказать нам про эти данные, то что вы сможете в них увидеть. Результатом должен быть Rmd файл с вашим анализом, лучше всего если вы продолжите работать в этом файле. Обязательно укажите свои имя, фамилию и группу.

Сегодня вы должны понять что за данные перед вами. Построить ряд графиков, которые помогут вам охаррактеризовать данные. И поставить вопросы, на которые можно будет ответить с помощью статистических тестов.


