---
title: "Project: plan, discussion and issues"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Этапы проекта

Порядок п.1-2 отличается для самостоятельных проектов и "стандартного" варианта

1. Придумать идею. 

2. Собрать команду

3. Создать репозиторий для совместной работы над проектом (GitHub) -- см. предыдущую лабораторную

4. Составить план действий

5. Распределить роли

6. Распределить задачи

7. Выполнить проект =))

+ Промежуточный и итоговый отчеты

+ Обсуждения

## Обязательные пункты плана

Эти пункты обязательно обсуждаются + содержатся в промежуточных отчетах (вопросы в Степике)

**Пункт 1. Данные**

* Есть данные / нет данных
* Ссылка на них, если есть. Описание того, как и когда они будут получены, если их нет
* Описание данных: формат, объем, как их можно загрузить и как начать с ними работать; переменные, их описание, где его можно посмотреть
* Очистка данных: нужна / не нужна, кто ее делает, как все члены группы могут понять, какая версия является актуальной, и где взять актуальную версию
* *Стандартный вариант:* <http://jmcauley.ucsd.edu/data/amazon/>

**Пункт 2. Планируемое представление результатов**

* что рекомендуется
* что представляет собой результат рекомендации
* что должен сделать / ввести пользователь, чтобы получить рекомендацию

**Пункт 3. Методы**

* какие методы и алгоритмы планируется использовать
* разведочный анализ: посмотреть основные закономерности
* *Обязательно:* как минимум, один из методов машинного обучения, изученный в прошлом семестре (кластеризация, классификация, PCA...)

**Пункт 4. Сроки**

* когда должна быть решена та или иная задача + кто ее решает

1. Роли в проекте могут распределяться по задачам.
   * Сбор данных.
   * Обработка данных.
   * Построение моделей.
   * Визуализация результатов.
   * Общее руководство и пинание всех ногами.
2. Все делают все...
